# Form implementation generated from reading ui file 'MainWinSignalSlog1.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.button_close = QtWidgets.QPushButton(parent=Form)
        self.button_close.setGeometry(QtCore.QRect(160, 120, 75, 23))
        self.button_close.setObjectName("button_close")

        self.retranslateUi(Form)
        self.button_close.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button_close.setText(_translate("Form", "關閉視窗"))
