# Form implementation generated from reading ui file 'MainForm.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.picture = QtWidgets.QLabel(parent=self.centralwidget)
        self.picture.setGeometry(QtCore.QRect(100, 10, 600, 500))
        self.picture.setText("")
        self.picture.setPixmap(QtGui.QPixmap("../../../../Blog/source/images/OS.jpg"))
        self.picture.setScaledContents(True)
        self.picture.setObjectName("picture")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.newfile_action = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme("document-new")
        self.newfile_action.setIcon(icon)
        self.newfile_action.setObjectName("newfile_action")
        self.open_action = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.open_action.setIcon(icon)
        self.open_action.setObjectName("open_action")
        self.close_action = QtGui.QAction(parent=MainWindow)
        self.close_action.setObjectName("close_action")
        self.open_calc_action = QtGui.QAction(parent=MainWindow)
        self.open_calc_action.setObjectName("open_calc_action")
        self.open_notepad_action = QtGui.QAction(parent=MainWindow)
        self.open_notepad_action.setObjectName("open_notepad_action")
        self.menu.addAction(self.newfile_action)
        self.menu.addAction(self.open_action)
        self.menu.addAction(self.close_action)
        self.menu.addAction(self.open_calc_action)
        self.menu.addAction(self.open_notepad_action)
        self.menubar.addAction(self.menu.menuAction())
        self.toolBar.addAction(self.newfile_action)
        self.toolBar.addAction(self.open_action)
        self.toolBar.addAction(self.close_action)
        self.toolBar.addAction(self.open_calc_action)
        self.toolBar.addAction(self.open_notepad_action)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "檔案"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.newfile_action.setText(_translate("MainWindow", "新建"))
        self.newfile_action.setShortcut(_translate("MainWindow", "Alt+N"))
        self.open_action.setText(_translate("MainWindow", "開啟"))
        self.open_action.setShortcut(_translate("MainWindow", "Alt+O"))
        self.close_action.setText(_translate("MainWindow", "關閉"))
        self.close_action.setShortcut(_translate("MainWindow", "Alt+C"))
        self.open_calc_action.setText(_translate("MainWindow", "計算機"))
        self.open_calc_action.setToolTip(_translate("MainWindow", "打開計算機"))
        self.open_notepad_action.setText(_translate("MainWindow", "記事本"))
